export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_HOLDER_REQUESTS = "GET_HOLDER_REQUESTS";
export const CREATE_REQUEST = "CREATE_REQUEST";
export const UPDATE_HOLDER_REQUEST_STATUS = "UPDATE_HOLDER_REQUEST_STATUS";

export const GET_ISSUER_REQUESTS = "GET_ISSUER_REQUESTS";
export const UPDATE_ISSUER_REQUEST = "UPDATE_ISSUER_REQUEST";

export const GET_VERIFIER_REQUESTS = "GET_VERIFIER_REQUESTS";
export const UPDATE_VERIFIER_REQUEST = "UPDATE_VERIFIER_REQUEST";

export const GET_RECORD_DETAIL = "GET_RECORD_DETAIL";
export const REMOVE_SELECTED_RECORD = "REMOVE_SELECTED_RECORD";